### ISSUE TITLE
My Crypto Graph Improvements

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1166]
https://projects.invisionapp.com/d/main#/console/15222689/316491951/preview 

1. Style tooltip hat appears on hover over graph, using our UI styleguide
2. Change hilight of token (also when hovering over graph) from blue border to dark background

**Comment by rhdelima** [comment]
@designhorf, Tooltip doesn't match with the design.
@oanamangiurea , Since we're improving My Crypto, should we change the gear icon to Manage Tokens button? or keep it as is. Thanks!
 
Expected:
![image](https://user-images.githubusercontent.com/10294014/57573336-b8ed1500-7458-11e9-8e17-ea7136efa434.png)

Actual:
![image](https://user-images.githubusercontent.com/10294014/57573330-9f4bcd80-7458-11e9-9993-bdd866292cb5.png)

**Comment by oanamangiurea** [comment]
@rhdelima the gear icon, and better functionality when adding will be addressed by a different issue in the future. Thank you.

**Comment by rhdelima** [comment]
@designhorf Sorry, I'm reopening this one since the tooltip is misplaced. See sample screenshot

![image](https://user-images.githubusercontent.com/10294014/59675486-ee271880-91f7-11e9-8e11-725f0c873569.png)

**Comment by designhorf** [comment]
Don't know why the html tooltip position is changed. Didn't find example in documentation.
First I'll working on more important tasks and then jump back to this one.

**Comment by designhorf** [comment]
For customised tooltip we need to use `tooltip: {isHtml: true}` parameter which turns tooltip format from `svg` to `html`. After triggered this option, can't control the position of tooltip. That's why I chose default setting with limited style modification.

**Comment by rhdelima** [comment]
Looks good for now. Note that the arrow on the tooltip is not implemented as per design. See screenshot

![image](https://user-images.githubusercontent.com/10294014/60488247-0c027c00-9cd4-11e9-8713-6c444f0f0b85.png)
