### ISSUE TITLE
Manage Application - wrong service displayed in Profile

### ISSUE THREAD

**Issue by oanamangiurea** [SelfKeyFoundation/Identity-Wallet#1363]
Under user profile we display the wrong service application

Tested on dev release

*Steps to reproduce: *
1. First use of the wallet, I try to open a bank account for Singapore
2. I don't create a DID (not relevant)
3. In SelfKey ID - manage application tab I see that I applied for Incorporations not bank accouns

![Screenshot 2019-06-27 at 11.07.47.png](https://images.zenhubusercontent.com/5b7beb7f8c0e917986992a6c/c67312aa-537e-4475-adb6-94230f0693e3)

----

Also message under status is not correct. I haven't submitted any documents yet, so in this case we need to change "Application started. Documents submitted. Please check your email for further instructions." to

"Application started. Waiting for payment" and use the styling with orange as in InVision https://projects.invisionapp.com/d/main#/console/15222689/346095676/preview

**Comment by andregoncalves** [comment]
That's an issue I already detected.
I'm currently working on it.

**Comment by andregoncalves** [comment]
@eduardosmoura I'm assigning this to you.

Until the scheduler (and associate vendor airtable) is released, we are going to have this issue because we are using the same rp for BAM as Incorporations.

Can we for now do a temporary fix, that detect the product name starts with Bank Account and replace Incorporations with Bank Accounts in the application? 

![Screen Shot 2019-07-09 at 11.27.06.png](https://images.zenhubusercontent.com/5be15edea977220c77bd265d/b0a4a3c3-b288-463d-a485-9789f6478931)

**Comment by rhdelima** [comment]
Looks good. Pass

![image](https://user-images.githubusercontent.com/10294014/61209970-b6938980-a72d-11e9-89da-19000ce87e29.png)
