### ISSUE TITLE
CORP1: UI - Corporate profile setup wizard

### ISSUE THREAD

**Issue by sk91** [SelfKeyFoundation/Identity-Wallet#1559]

**Comment by eduardosmoura** [comment]
@oanamangiurea, @sk91, or @andregoncalves, do we have any design screen to guide us to build this feature?

**Comment by oanamangiurea** [comment]
@eduardosmoura https://projects.invisionapp.com/d/main#/console/15222689/316560291/preview and https://projects.invisionapp.com/d/main#/console/15222689/316560292/preview 

For 2nd screen, if it's legal entity type instead of individual, we need to ask for same fields as in the 1st screen (so instead of first name, last name, etc..), keeping the shares owned field

**Comment by eduardosmoura** [comment]
Thank you so much @oanamangiurea!

**Comment by rhdelima** [comment]
Looks good. Pass
