### ISSUE TITLE
Dashboard update

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#1946]
Details in the 1st comment 👇

- [x] My Tokens widget design implementation
- [x] My Tokens functions
- [x] Buy KEY widget design implementation
- [x] Buy KEY popup
- [x] Transactions widget design implementation
- [x] Transactions filter popup
- [x] Marketplace Application widget design implementation
- [x] Marketplace Application fetch data
- [x] Empty Marketplace Application route to marketplace
- [x] Marketplace Application route to applications
- [x] SK Profile widget design implementation
- [x] SK Profile w/ real data
- [x] SK Profile w/ route
- [ ] Update Send Custom Token modal - https://projects.invisionapp.com/d/main#/console/15222689/316491962/preview

**Comment by oanamangiurea** [comment]
Current dashboard that needs to be implemented (until we'll have partnership with a 3rd party to buy from the wallet) is this one: 

Full state: https://projects.invisionapp.com/d/main#/console/15222689/398680342/preview 
Empty state: https://projects.invisionapp.com/d/main#/console/15222689/398676277/preview

Extra new screens related to this one:

1. Transactions Lists with filters https://projects.invisionapp.com/d/main#/console/15222689/397678445/preview 
2. Get Key modal: https://projects.invisionapp.com/d/main#/console/15222689/399057839/preview

@designhorf  I will remove the on hold label now. Please give this a new estimate for the extra screens or break them into other tasks if needed

**Comment by rhdelima** [comment]
@designhorf Please see issues below:
1. Too much space on the left of My Tokens
2. Missing logo for KEY and ETH
3. Update Selfkey to SelfKey
4. Missing `$` on converted USD value
5. Transactions are not fetching
![image](https://user-images.githubusercontent.com/10294014/74639979-c84c7c00-51a9-11ea-98ad-13eaf2bd38b3.png)
6. Incorrect icon on `Send/Receive Tokens` modal
7. Missing Receive tab on `Send/Receive Tokens` modal
8. Unable to send ETH since it is missing on the drop down.
9. When clicking token on dashboard, it opens `Send/Receive Tokens` modal however token is not pre-populated with token selected.

![image](https://user-images.githubusercontent.com/10294014/74640477-91c33100-51aa-11ea-9edf-5ac36572d341.png)

**Comment by designhorf** [comment]
@rhdelima got it, will fix those but `Send/Receive Tokens` have separate task https://github.com/SelfKeyFoundation/Identity-Wallet/issues/2036 please don't check it.

**Comment by oanamangiurea** [comment]
Also for me it shows a scrollbar placement in the latest dev build https://gyazo.com/0381cceb33d6102d1741db3e6cee40d3

**Comment by rhdelima** [comment]
@designhorf Please see additional layout issue
![image](https://user-images.githubusercontent.com/10294014/76742773-97f9fc80-67ac-11ea-9143-f699adbc5cee.png)

**Comment by oanamangiurea** [comment]
@rhdelima that's the intended behaviour if we have lots of digits after .

**Comment by rhdelima** [comment]
Failing this one. Truncated display when adding more tokens. See screenshot.

![image](https://user-images.githubusercontent.com/10294014/77749455-05cfdf00-705d-11ea-8130-d620a67adddb.png)

**Comment by andregoncalves** [comment]
The list is scrollable. @oanamangiurea is this according to design?

![Screenshot 2020-03-31 at 18.11.11.png](https://images.zenhubusercontent.com/5be15edea977220c77bd265d/14ee5532-20ee-42f3-a5d7-e371bbccb1cb)

**Comment by oanamangiurea** [comment]
@andregoncalves yes, if it's scrollable then it's ok
