### ISSUE TITLE
Send Custom Token modal

### ISSUE THREAD

**Issue by designhorf** [SelfKeyFoundation/Identity-Wallet#2036]

**Comment by rhdelima** [comment]
@designhorf Failing this one.

1. Should show available balance after token is selected. Currently, it is only updated once user inputs amount
![image](https://user-images.githubusercontent.com/10294014/76743649-ea87e880-67ad-11ea-9751-e6d09a0c77ef.png)

2. Nothing happens when clicking Print on Receive screen
3. White screen is shown when clicking Email
http://recordit.co/4lsxyVHkSV
4. When opening Receive screen without selecting a token yet, it shows `Your Ethereum address to receive custom`. @oanamangiurea, Can you confirm if you're good with this? Shouldn't we replace `custom` on the message while no token is selected yet? 
![image](https://user-images.githubusercontent.com/10294014/76744395-21123300-67af-11ea-8b09-c3b79eb39723.png)

**Comment by oanamangiurea** [comment]
@rhdelima @designhorf the desired behaviour is to only show the Token Dropdown at first, and the tabs will only appear after the user has selected something. That way we fix 2 of the issues above, and it's more visible to the user that he has to choose a token first.

**Comment by andregoncalves** [comment]
@rhdelima ready for testing.

**Comment by rhdelima** [comment]
Looks good. Pass

**Comment by oanamangiurea** [comment]
Reopening this because it' not fully done yet. As per any other dropdown in the wallet, the input Token should have a placeholder "Select..."

**Comment by rhdelima** [comment]
@oanamangiurea Let me know if you're good with this.

![image](https://user-images.githubusercontent.com/10294014/77993238-46c83c00-735a-11ea-8ad4-9cf1f9dcfa2d.png)

**Comment by oanamangiurea** [comment]
@rhdelima yes, it's ok
