### ISSUE TITLE
Set $1000 USD tx max for Totle Swap

### ISSUE THREAD

**Issue by andregoncalves** [SelfKeyFoundation/Identity-Wallet#2174]

**Comment by oanamangiurea** [comment]
@andregoncalves I added a small text under the input saying Max $1000/Swap [![Screenshot from Gyazo](https://gyazo.com/d07e7cda144ed15f43e3f07ac260c848/raw)](https://gyazo.com/d07e7cda144ed15f43e3f07ac260c848) so expected behavior from this:

1. If user will input more than $1000 - input validation error, saying "Max amount to swap is $1000 USD"
2. When pressed the "Max" button either put $1000 if the user holds more funds, or the max of his funds, whichever is higher.

**Comment by andregoncalves** [comment]
idea: add support for max value via env variables to facilitate testing.

**Comment by rhdelima** [comment]
@andregoncalves @oanamangiurea 
Unable to verify the expected behaviors since:
1. Clicking MAX button will set amount to limit and not the available balance
2. Cannot set amount greater than limit.
http://recordit.co/I6Ye1VSVa0

Please confirm if we're good with this.

**Comment by oanamangiurea** [comment]
@rhdelima yes, I'm good with this behaviour
@andregoncalves one little thing: that text saying Max 1000$/swap should be right aligned with the input above, you can see it in Ralph's video that for a different amount it is not
