### ISSUE TITLE
UI for Selfkey ID is not responsive 

### ISSUE THREAD

**Issue by rodrigopavezi** [SelfKeyFoundation/Identity-Wallet#439]
There is no scroll bar or the content does not fit the screen.

![SelfKeyID-creation-doesnt-fit-in-screen.jpg](https://images.zenhubusercontent.com/5b7bd3b852bce06c3c5c53c0/94f2a54b-5b4c-4bfb-9696-21438b21a4af)

**Comment by felipewer** [comment]
I'm having the same problem on Linux with Gnome Desktop. I'm not able to confirm the terms agreement because I cannot decrease the size of the window passed this point nor scroll down. In effect this makes the wallet useless.

![selfkey_terms_unresisable](https://user-images.githubusercontent.com/9268918/47931623-19016e00-deae-11e8-9cc4-0ffc0e0fef38.png)
