### ISSUE TITLE
Incorporation data issue on kycc instance

### ISSUE THREAD

**Issue by rhdelima** [SelfKeyFoundation/Identity-Wallet#839]
1. Image is not loading on preview
2. Utility Bill is not uploaded
3. Map CV/Resume and Professional Reference Letter to correct documents on wallet
4. Forms below have status 'waiting for fill'
      - Belize IBC Order Form
      - Individual KYC Form
5. Incorrect Title and Question for Middle Name

Recording: http://recordit.co/tUtaIdzPDY
Record: https://apiv2.instance.kyc-chain.com/management/#/member/kyc-process/individual/item/5c7fafd87fc188846fc28731/overview

**Comment by rodrigopavezi** [comment]
@andregoncalves can I leave this one with you? cheers

**Comment by andregoncalves** [comment]
I looked into this:

1. Should be fixed now for new applications with kyc-chain updates, however the documents uploaded should be tested with the final kyc-chain instance for flag theory (not the test instance).
2. Same as 1
3. The kyc template is a test template was setup this way, should be corrected in the production instance.
4. Those forms will not be sent by the wallet, they will be filled afterwards by the users, so that status is correct.
5. Same as 4.
